spring:
  application:
    name: "camunda"
  cloud:
    config:
      enabled: "false"
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo


---
spring:
  cloud:
    config:
      enabled: "true"
      fail-fast: "true"
      retry:
        maxAttempts: "10"
        multiplier: "1.5"
        initial-interval: "5000"
        max-interval: "60000"
  config:
    activate:
      on-profile: config-server
    import: "configserver:"